services:
  apollo_database:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app_user
      POSTGRES_DB: app_db
      POSTGRES_PASSWORD: app_password
    ports:
      - "5432:5432"
    networks:
      - apollo_network

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    depends_on:
      - apollo_database
    environment:
      DATABASE_URL: postgresql+psycopg://app_user:app_password@apollo_database:5432/app_db
    networks:
      - apollo_network

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: frontend
    ports:
      - "3000:80"
    stdin_open: true
    tty: true
    networks:
      - apollo_network

volumes:
  pgdata:

networks:
  apollo_network:
    driver: bridge