"""empty message

Revision ID: 024b1d4c38a9
Revises: 4c1355e14353
Create Date: 2024-10-12 13:17:25.077057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '024b1d4c38a9'
down_revision: Union[str, None] = '4c1355e14353'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('promocoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('porcentagem_desconto', sa.Float(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('produtos', sa.Column('criado_em', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('produtos', sa.Column('atualizado_em', sa.DateTime(), nullable=False))
    op.add_column('produtos', sa.Column('categoria_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'produtos', 'categorias', ['categoria_id'], ['id'])
    op.drop_column('produtos', 'preco_promocional')
    op.drop_column('produtos', 'categoria')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produtos', sa.Column('categoria', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('produtos', sa.Column('preco_promocional', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'produtos', type_='foreignkey')
    op.drop_column('produtos', 'categoria_id')
    op.drop_column('produtos', 'atualizado_em')
    op.drop_column('produtos', 'criado_em')
    op.drop_table('promocoes')
    op.drop_table('categorias')
    # ### end Alembic commands ###
